name: Build Project

on:
  push:
    branches: ["dev"]

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "build"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0
        with:
          submodules: true
          fetch-depth: 1

      - name: Setup Java
        uses: actions/setup-java@v5.0.0
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5.0.0
        with:
          cache-cleanup: always
          cache-disabled: true

      - name: Grant Execute Permission For Gradlew
        run: chmod +x gradlew

      - name: Build jar
        run: ./gradlew build

      - name: Fetch mods
        run: |
          cd Modpack-Modern
          java -jar pakku.jar fetch

      - name: Copy Modpack
        run: |
          mkdir run
          mv ./Modpack-Modern/mods ./run
          mv ./Modpack-Modern/kubejs ./run
          mv ./Modpack-Modern/resourcepacks ./run
          ls -l run/mods
          ls -l run/kubejs
          ls -l run/resourcepacks

      - name: Build Website
        run: |
          rm -rf output
          java -jar build/libs/field-guide-tfg-1.0.0.jar -i run -o output

      #- name: Setup Pages
      #  uses: actions/configure-pages@v5

      #- name: Upload Pages artifact
      #  uses: actions/upload-pages-artifact@v3
      #  with:
      #    path: 'www'
